package tifmo

/**
 * Local interfaces for various language resources, sometimes with the resource itself. 
 * 
 * Classes from this package can be used by classes in [[tifmo.knowledge]] 
 * package and [[tifmo.proc]] package. The principle is that classes in [[tifmo.knowledge]] 
 * package should not use any external packages, so any external packages used for resources 
 * should be wrapped here.
 */
package object resource {}
